-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================

-- 创建静态网站托管存储桶
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'portfolio-static',
  'portfolio-static', 
  true,
  52428800,
  ARRAY['text/html', 'text/css', 'application/javascript', 'image/png', 'image/jpeg', 'image/gif', 'image/svg+xml', 'image/webp', 'application/json', 'text/plain']
);

-- 创建允许所有人读取文件的RLS策略
CREATE POLICY "公开读取静态文件" ON storage.objects
FOR SELECT USING (bucket_id = 'portfolio-static');

-- 创建允许认证用户上传文件的RLS策略  
CREATE POLICY "认证用户可上传静态文件" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'portfolio-static' AND auth.role() = 'authenticated');